<?php

function auto_parts_cron() {
  module_load_include('inc', 'auto_parts', 'includes/export_yml');
  $export = new ExportToYml();
  $export->export();
}

/**
 * Implements hook_menu().
 */
function auto_parts_menu() {
  $items = array();
  $items['auto-pars/export/excel'] = array(
    'title' => 'Export to excel',
    'page callback' => 'auto_parts_export',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/export_excel.inc',
  );
  return $items;
}


function auto_parts_export() {
  $export = new ExportToExcel();
  $export->export();
  return '<div>22222</div>';
}